/// Emoji shortcodes for `:code:` autocomplete — the common GitHub set.
library;

const Map<String, String> emojiShortcodes = {
  'smile': '😄', 'smiley': '😃', 'grin': '😁', 'grinning': '😀',
  'laughing': '😆', 'joy': '😂', 'rofl': '🤣', 'sweat_smile': '😅',
  'wink': '😉', 'blush': '😊', 'innocent': '😇', 'slightly_smiling_face': '🙂',
  'upside_down_face': '🙃', 'relaxed': '☺️', 'heart_eyes': '😍',
  'kissing_heart': '😘', 'star_struck': '🤩', 'thinking': '🤔',
  'neutral_face': '😐', 'expressionless': '😑', 'smirk': '😏',
  'unamused': '😒', 'roll_eyes': '🙄', 'grimacing': '😬', 'relieved': '😌',
  'pensive': '😔', 'sleepy': '😪', 'sleeping': '😴', 'mask': '😷',
  'sunglasses': '😎', 'nerd_face': '🤓', 'confused': '😕', 'worried': '😟',
  'frowning': '😦', 'open_mouth': '😮', 'astonished': '😲', 'flushed': '😳',
  'scream': '😱', 'fearful': '😨', 'cry': '😢', 'sob': '😭',
  'disappointed': '😞', 'angry': '😠', 'rage': '😡', 'triumph': '😤',
  'zzz': '💤', 'skull': '💀', 'ghost': '👻', 'alien': '👽', 'robot': '🤖',
  'poop': '💩', 'clown_face': '🤡',
  'wave': '👋', 'raised_hand': '✋', 'ok_hand': '👌', 'v': '✌️',
  'crossed_fingers': '🤞', 'thumbsup': '👍', '+1': '👍', 'thumbsdown': '👎',
  '-1': '👎', 'fist': '✊', 'clap': '👏', 'raised_hands': '🙌', 'pray': '🙏',
  'handshake': '🤝', 'muscle': '💪', 'point_up': '☝️', 'point_right': '👉',
  'point_left': '👈', 'point_down': '👇', 'writing_hand': '✍️',
  'eyes': '👀', 'eye': '👁️', 'ear': '👂', 'nose': '👃', 'brain': '🧠',
  'tongue': '👅', 'lips': '👄',
  'heart': '❤️', 'orange_heart': '🧡', 'yellow_heart': '💛',
  'green_heart': '💚', 'blue_heart': '💙', 'purple_heart': '💜',
  'black_heart': '🖤', 'broken_heart': '💔', 'two_hearts': '💕',
  'sparkling_heart': '💖', 'heartpulse': '💗', 'cupid': '💘',
  'fire': '🔥', 'sparkles': '✨', 'star': '⭐', 'star2': '🌟', 'zap': '⚡',
  'boom': '💥', 'dizzy': '💫', 'sweat_drops': '💦', 'droplet': '💧',
  'sun_with_face': '🌞', 'sunny': '☀️', 'cloud': '☁️', 'rainbow': '🌈',
  'umbrella': '☔', 'snowflake': '❄️', 'snowman': '⛄', 'comet': '☄️',
  'earth_africa': '🌍', 'earth_americas': '🌎', 'earth_asia': '🌏',
  'crescent_moon': '🌙', 'full_moon': '🌕', 'new_moon': '🌑',
  'dog': '🐶', 'cat': '🐱', 'mouse': '🐭', 'hamster': '🐹', 'rabbit': '🐰',
  'fox_face': '🦊', 'bear': '🐻', 'panda_face': '🐼', 'koala': '🐨',
  'tiger': '🐯', 'lion': '🦁', 'cow': '🐮', 'pig': '🐷', 'frog': '🐸',
  'monkey_face': '🐵', 'see_no_evil': '🙈', 'hear_no_evil': '🙉',
  'speak_no_evil': '🙊', 'chicken': '🐔', 'penguin': '🐧', 'bird': '🐦',
  'baby_chick': '🐤', 'duck': '🦆', 'eagle': '🦅', 'owl': '🦉', 'bat': '🦇',
  'wolf': '🐺', 'horse': '🐴', 'unicorn': '🦄', 'bee': '🐝', 'bug': '🐛',
  'butterfly': '🦋', 'snail': '🐌', 'snake': '🐍', 'turtle': '🐢',
  'fish': '🐟', 'dolphin': '🐬', 'whale': '🐳', 'octopus': '🐙',
  'crab': '🦀', 'shark': '🦈',
  'apple': '🍎', 'banana': '🍌', 'grapes': '🍇', 'strawberry': '🍓',
  'watermelon': '🍉', 'peach': '🍑', 'cherries': '🍒', 'lemon': '🍋',
  'pineapple': '🍍', 'avocado': '🥑', 'eggplant': '🍆', 'corn': '🌽',
  'hot_pepper': '🌶️', 'bread': '🍞', 'cheese': '🧀', 'egg': '🥚',
  'bacon': '🥓', 'pancakes': '🥞', 'pizza': '🍕', 'hamburger': '🍔',
  'fries': '🍟', 'hotdog': '🌭', 'taco': '🌮', 'burrito': '🌯',
  'ramen': '🍜', 'spaghetti': '🍝', 'sushi': '🍣', 'bento': '🍱',
  'curry': '🍛', 'rice': '🍚', 'cake': '🍰', 'birthday': '🎂',
  'cookie': '🍪', 'chocolate_bar': '🍫', 'candy': '🍬', 'lollipop': '🍭',
  'doughnut': '🍩', 'ice_cream': '🍨', 'coffee': '☕', 'tea': '🍵',
  'beer': '🍺', 'beers': '🍻', 'wine_glass': '🍷', 'cocktail': '🍸',
  'tropical_drink': '🍹', 'champagne': '🍾',
  'soccer': '⚽', 'basketball': '🏀', 'football': '🏈', 'baseball': '⚾',
  'tennis': '🎾', 'volleyball': '🏐', '8ball': '🎱', 'golf': '⛳',
  'dart': '🎯', 'bowling': '🎳', 'video_game': '🎮', 'game_die': '🎲',
  'chess_pawn': '♟️', 'jigsaw': '🧩', 'trophy': '🏆', 'medal_sports': '🏅',
  'first_place_medal': '🥇', 'second_place_medal': '🥈',
  'third_place_medal': '🥉',
  'car': '🚗', 'taxi': '🚕', 'bus': '🚌', 'police_car': '🚓',
  'fire_engine': '🚒', 'ambulance': '🚑', 'truck': '🚚', 'tractor': '🚜',
  'bike': '🚲', 'motorcycle': '🏍️', 'rocket': '🚀', 'airplane': '✈️',
  'helicopter': '🚁', 'ship': '🚢', 'sailboat': '⛵', 'anchor': '⚓',
  'train': '🚋', 'metro': '🚇', 'tram': '🚊',
  'house': '🏠', 'office': '🏢', 'hospital': '🏥', 'bank': '🏦',
  'hotel': '🏨', 'school': '🏫', 'church': '⛪', 'castle': '🏰',
  'tent': '⛺', 'desert_island': '🏝️', 'mountain': '⛰️', 'volcano': '🌋',
  'watch': '⌚', 'iphone': '📱', 'computer': '💻', 'desktop_computer': '🖥️',
  'keyboard': '⌨️', 'printer': '🖨️', 'tv': '📺', 'camera': '📷',
  'video_camera': '📹', 'movie_camera': '🎥', 'telephone': '☎️',
  'battery': '🔋', 'electric_plug': '🔌', 'bulb': '💡', 'flashlight': '🔦',
  'candle': '🕯️', 'wastebasket': '🗑️', 'moneybag': '💰', 'dollar': '💵',
  'credit_card': '💳', 'gem': '💎', 'wrench': '🔧', 'hammer': '🔨',
  'gear': '⚙️', 'pick': '⛏️', 'nut_and_bolt': '🔩', 'knife': '🔪',
  'gun': '🔫', 'bomb': '💣', 'shield': '🛡️', 'key': '🔑', 'lock': '🔒',
  'unlock': '🔓', 'link': '🔗', 'paperclip': '📎', 'scissors': '✂️',
  'pencil2': '✏️', 'pen': '🖊️', 'paintbrush': '🖌️', 'crayon': '🖍️',
  'memo': '📝', 'pencil': '📝', 'book': '📖', 'books': '📚',
  'notebook': '📓', 'ledger': '📒', 'page_facing_up': '📄',
  'newspaper': '📰', 'bookmark': '🔖', 'label': '🏷️', 'email': '✉️',
  'envelope': '✉️', 'inbox_tray': '📥', 'outbox_tray': '📤',
  'package': '📦', 'mailbox': '📫', 'calendar': '📆', 'chart': '💹',
  'bar_chart': '📊', 'chart_with_upwards_trend': '📈',
  'chart_with_downwards_trend': '📉', 'clipboard': '📋', 'pushpin': '📌',
  'round_pushpin': '📍', 'triangular_ruler': '📐', 'straight_ruler': '📏',
  'file_folder': '📁', 'open_file_folder': '📂', 'card_index': '📇',
  'mag': '🔍', 'mag_right': '🔎', 'microscope': '🔬', 'telescope': '🔭',
  'bell': '🔔', 'no_bell': '🔕', 'megaphone': '📣', 'loudspeaker': '📢',
  'hourglass': '⌛', 'alarm_clock': '⏰', 'stopwatch': '⏱️',
  'clock1': '🕐',
  'check': '✔️', 'heavy_check_mark': '✔️', 'white_check_mark': '✅',
  'x': '❌', 'negative_squared_cross_mark': '❎', 'warning': '⚠️',
  'question': '❓', 'exclamation': '❗', 'bangbang': '‼️',
  'interrobang': '⁉️', 'no_entry': '⛔', 'no_entry_sign': '🚫',
  'red_circle': '🔴', 'green_circle': '🟢', 'blue_circle': '🔵',
  'yellow_circle': '🟡', 'orange_circle': '🟠', 'purple_circle': '🟣',
  'white_circle': '⚪', 'black_circle': '⚫', 'red_square': '🟥',
  'green_square': '🟩', 'blue_square': '🟦', 'infinity': '♾️',
  'recycle': '♻️', 'copyright': '©️', 'registered': '®️', 'tm': '™️',
  'arrow_up': '⬆️', 'arrow_down': '⬇️', 'arrow_left': '⬅️',
  'arrow_right': '➡️', 'arrows_counterclockwise': '🔄',
  'hash': '#️⃣', 'asterisk': '*️⃣', '100': '💯', 'ok': '🆗', 'new': '🆕',
  'free': '🆓', 'sos': '🆘', 'cool': '🆒',
  'tada': '🎉', 'confetti_ball': '🎊', 'balloon': '🎈', 'gift': '🎁',
  'ribbon': '🎀', 'crown': '👑', 'ring': '💍', 'christmas_tree': '🎄',
  'jack_o_lantern': '🎃', 'fireworks': '🎆', 'sparkler': '🎇',
  'music': '🎵', 'musical_note': '🎵', 'notes': '🎶', 'microphone': '🎤',
  'headphones': '🎧', 'guitar': '🎸', 'violin': '🎻', 'trumpet': '🎺',
  'drum': '🥁', 'art': '🎨', 'clapper': '🎬', 'ticket': '🎫',
  'circus_tent': '🎪', 'performing_arts': '🎭',
  'flag_white': '🏳️', 'flag_black': '🏴', 'checkered_flag': '🏁',
  'triangular_flag_on_post': '🚩', 'rainbow_flag': '🏳️‍🌈',
};
